/**
 * Conformance against the server's golden protocol vectors.
 *
 * The signing protocol is implemented independently in repuwave-core, in the
 * Python SDK, and here. They must produce byte-identical canonical payloads, or
 * every signature this SDK produces fails verification in production -- a
 * failure that surfaces on the integrator's side, as a signature mismatch, with
 * nothing pointing back here.
 *
 * Until this file existed, the whole cross-repo drift guard covered Python only.
 * `signer.test.ts` asserted two canonical strings that were typed into the test
 * by hand, so regenerating the vectors in repuwave-core changed nothing here and
 * Node could drift silently while its own suite stayed green.
 *
 * `conformance/protocol_vectors.json` is generated by
 * scripts/generate_protocol_vectors.py in repuwave-core and checked in. This
 * suite asserts the SDK reproduces every vector byte-for-byte -- no Django, no
 * Rust extension, no cross-repo clone, so there is no reason to skip it.
 *
 * If this fails, the implementations have diverged. Decide which is wrong, fix
 * it, and regenerate the vectors in the same change.
 */

import { readFileSync, existsSync } from "fs";
import { join } from "path";
import { Ed25519Signer } from "../src/signer";

const VECTORS_PATH = join(__dirname, "..", "..", "conformance", "protocol_vectors.json");

interface Vector {
  name: string;
  uaid: string;
  timestamp: number;
  body: string | null;
  canonical: string;
}

function loadVectors(): Vector[] {
  if (!existsSync(VECTORS_PATH)) {
    throw new Error(
      `${VECTORS_PATH} is missing. It is generated in the repuwave-core ` +
        `repository by scripts/generate_protocol_vectors.py and checked in here. ` +
        `Without it this suite proves nothing about compatibility.`,
    );
  }
  return JSON.parse(readFileSync(VECTORS_PATH, "utf8")).vectors;
}

describe("protocol conformance", () => {
  const vectors = loadVectors();

  it("has a substantive vector set", () => {
    // A single trivial vector would not catch a real divergence.
    expect(vectors.length).toBeGreaterThanOrEqual(5);
  });

  it("reproduces every golden vector byte-for-byte", () => {
    expect(vectors.length).toBeGreaterThan(0);

    for (const v of vectors) {
      const actual = Ed25519Signer.buildCanonicalPayload(
        v.uaid,
        v.timestamp,
        v.body ?? undefined,
      );

      // Jest's expect() takes no message argument, so the diagnostic is raised
      // directly. A bare toBe() here would print two long JSON strings and
      // leave the reader to spot the difference and guess why it matters.
      if (actual !== v.canonical) {
        throw new Error(
          `case "${v.name}" diverged.\n` +
            `  server: ${v.canonical}\n` +
            `  sdk:    ${actual}\n` +
            `Every signature this SDK produces will fail verification until ` +
            `these agree. Decide which is wrong, fix it, and regenerate the ` +
            `vectors in the same change.`,
        );
      }
      expect(actual).toBe(v.canonical);
    }
  });

  it("keeps keys sorted", () => {
    // Object insertion order would pass locally and fail against the server.
    for (const v of vectors) {
      expect(v.canonical.indexOf("body_hash")).toBeLessThan(v.canonical.indexOf("timestamp"));
      expect(v.canonical.indexOf("timestamp")).toBeLessThan(v.canonical.indexOf("uaid"));
    }
  });

  it("emits no whitespace", () => {
    // Separators are (',', ':'). Any space changes the hash.
    for (const v of vectors) {
      expect(v.canonical).not.toContain(" ");
    }
  });

  it("treats an empty body the same as an absent one", () => {
    // A truthiness check rather than an explicit undefined check would hash the
    // empty string and diverge from the server.
    expect(Ed25519Signer.buildCanonicalPayload("u", 1.0, "")).toBe(
      Ed25519Signer.buildCanonicalPayload("u", 1.0, undefined),
    );
  });
});
