"""
Conformance against the server's golden protocol vectors.

The signing protocol is implemented twice, independently: in `Ed25519Service`
(the server, in repuwave-core) and in this SDK. They must produce byte-identical
canonical payloads, or every signature this SDK produces fails verification in
production — a failure that appears on the integrator's side, as a signature
mismatch, with nothing pointing back here.

Nothing tested that across the repository boundary. During the Ed25519 migration
this suite imported a class that no longer existed and failed at *collection*, so
it reported nothing for an entire crypto migration. That is the failure this file
exists to make impossible.

How it works: `conformance/protocol_vectors.json` is generated by
`scripts/generate_protocol_vectors.py` in repuwave-core and checked in here. This
suite asserts the SDK reproduces every vector byte-for-byte. No Django, no Rust
extension, no cross-repo clone — just a JSON file and the SDK's own code, so this
runs anywhere and there is no reason to skip it.

If this fails, the two implementations have diverged. Decide which is wrong, fix
it, and regenerate the vectors in the same change.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from repuwave_sdk.signer import Ed25519Signer

VECTORS_PATH = Path(__file__).resolve().parents[2] / "conformance" / "protocol_vectors.json"


@pytest.fixture(scope="module")
def vectors() -> dict:
    if not VECTORS_PATH.is_file():
        pytest.fail(
            f"{VECTORS_PATH} is missing. It is generated in the repuwave-core "
            f"repository by scripts/generate_protocol_vectors.py and checked in "
            f"here. Without it this suite proves nothing about compatibility."
        )
    return json.loads(VECTORS_PATH.read_text())


class TestProtocolConformance:
    """The SDK matches the server's canonical form exactly."""

    def test_vectors_file_is_substantive(self, vectors):
        """A single trivial vector would not catch a real divergence."""
        assert len(vectors["vectors"]) >= 5

    def test_every_vector_reproduces(self, vectors):
        """
        Every golden vector reproduces byte-for-byte.

        Iterates rather than parametrising over a hardcoded range: a fixed range
        pads the run with meaningless skips when vectors are added or removed,
        and a skip reads like coverage. Asserting inside one test keeps the
        count honest, and the failure message names the case.
        """
        cases = vectors["vectors"]
        assert cases, "no vectors to check"

        for case in cases:
            body = case["body"]
            body_bytes = body.encode("utf-8") if body is not None else None

            actual = Ed25519Signer.build_canonical_payload(
                case["uaid"], case["timestamp"], body_bytes
            )

            assert actual == case["canonical"], (
                f"case {case['name']!r} diverged.\n"
                f"  server: {case['canonical']!r}\n"
                f"  sdk:    {actual!r}\n"
                f"Every signature this SDK produces will fail verification "
                f"until these agree."
            )

    def test_key_order_matches(self, vectors):
        """Keys are sorted; a dict iteration order would pass locally and fail here."""
        for case in vectors["vectors"]:
            canonical = case["canonical"]
            assert canonical.index("body_hash") < canonical.index("timestamp")
            assert canonical.index("timestamp") < canonical.index("uaid")

    def test_no_whitespace_in_output(self, vectors):
        """Separators are (',', ':'). Any space changes the hash."""
        for case in vectors["vectors"]:
            assert " " not in case["canonical"]
            assert ", " not in case["canonical"]

    def test_empty_body_matches_absent_body(self):
        """
        b"" and None must produce the same payload.

        A truthiness check rather than `is not None` would hash the empty bytes
        and diverge from the server. Asserted directly so it holds even if the
        vector covering it is ever edited away.
        """
        assert Ed25519Signer.build_canonical_payload(
            "u", 1.0, b""
        ) == Ed25519Signer.build_canonical_payload("u", 1.0, None)

    def test_timestamp_formatting_matches(self):
        """
        Floats serialise without reformatting.

        `1715040000.0` must not become `1.7e+09` or lose the trailing `.0`.
        The classic two-serialiser divergence.
        """
        integral = Ed25519Signer.build_canonical_payload("u", 1715040000.0, None)
        fractional = Ed25519Signer.build_canonical_payload("u", 1700000000.123, None)

        assert "1715040000.0" in integral
        assert "1700000000.123" in fractional


class TestSignatureConformance:
    """What the SDK signs is what the server verifies."""

    def test_signature_verifies_under_pynacl(self, vectors):
        """
        A signature over a golden payload verifies with the standard library.

        Checked with PyNaCl directly rather than the SDK's own verify path, so
        this does not merely confirm the SDK agrees with itself. PyNaCl is the
        same primitive the server's Rust extension implements.
        """
        import hashlib

        from nacl.signing import VerifyKey

        case = vectors["vectors"][0]
        private_key, public_key = Ed25519Signer.generate_keypair()
        signer = Ed25519Signer(private_key)

        signature = signer.sign(case["canonical"])
        digest = hashlib.sha256(case["canonical"].encode("utf-8")).digest()

        # Raises BadSignatureError if the SDK hashed or encoded differently.
        VerifyKey(bytes.fromhex(public_key)).verify(digest, bytes.fromhex(signature))

    def test_the_signed_hash_is_sha256_of_the_canonical_form(self):
        """
        The SDK signs sha256(canonical), not canonical itself.

        If this changed, the server would reject every signature — and the
        failure would look like a key problem rather than an encoding one.
        """
        import hashlib

        from nacl.signing import VerifyKey

        private_key, public_key = Ed25519Signer.generate_keypair()
        signer = Ed25519Signer(private_key)
        payload = Ed25519Signer.build_canonical_payload("u", 1.0, b"body")

        signature = signer.sign(payload)
        digest = hashlib.sha256(payload.encode("utf-8")).digest()

        # Verifying the digest must succeed; verifying the raw payload must not.
        VerifyKey(bytes.fromhex(public_key)).verify(digest, bytes.fromhex(signature))

        with pytest.raises(Exception):
            VerifyKey(bytes.fromhex(public_key)).verify(
                payload.encode("utf-8"), bytes.fromhex(signature)
            )
